name: 'demo'

config-version: 2
version: '0.1'

profile: 'demo'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

vars:
  data_diff:
    datasource_id: 6357 # from datafold Data Sources page
    prod_database: DEV
    prod_schema: production_sung

models:
  ## see docs: https://docs.elementary-data.com/
  elementary:
    +schema: elementary
    enabled: "{{ target.name == 'prod' }}"
    # +meta:
    #   datafold:
    #     datadiff:
    #       never_diff: true
  demo:
      materialized: table
      staging:
        materialized: view
      # +meta:
      #   datafold:
      #     datadiff:
      #       never_diff: true