demo:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: BYA42734

      # User/password auth
      user: sung
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"

      role: DEMO_ROLE
      database: DEV
      warehouse: DEMO
      schema: development_sung
      threads: 24
      client_session_keep_alive: True
      query_tag:

    prod:
      type: snowflake
      account: bya42734

      # User/password auth
      user: sung
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"

      role: DEMO_ROLE
      database: DEV
      warehouse: DEMO
      schema: production_sung
      threads: 24
      client_session_keep_alive: True
      query_tag:

    duck:
      type: duckdb
      schema: development
      path: 'datafold_demo.duckdb'
      # path: 'md:datafold_demo?motherduck_token={{ env_var("motherduck_token")}}'
      threads: 16
