name: dbt prod

# Run this job on a push to the main branch or at 2AM
on:
  push:
    branches:
      - main
  schedule: # Run the pipeline at 2AM
    - cron: '0 2 * * *'

jobs:
  run:
    # This is the docker image used for the CI container
    runs-on: ubuntu-20.04

    steps:
        # Pull code from your Github repo into the container
      - name: checkout
        uses: actions/checkout@v2

        # Install Python 3.8, this is required to run dbt
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

        # Install Python packages defined in requirements.txt (dbt and dependencies)
      - name: install requirements
        run: pip install -q -r requirements.txt

        # Install dbt packages defined in packages.yml
      - name: dbt deps
        run: dbt deps

        # Run and test dbt models
      - name: dbt build
        run: dbt build --full-refresh --profiles-dir ./ --target prod
        env:
          # Secrets are pulled from the Github Actions secrets setting
          # See: https://docs.github.com/en/actions/security-guides/encrypted-secrets
          # SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          # SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          # SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          # SNOWFLAKE_SCHEMA: "${{ 'production_sung' }}"

        # Use the Datafold sdk to create a diff and write results to the PR
      - name: submit artifacts to datafold
        run: |
          set -ex
          datafold dbt upload --ci-config-id 238 --run-type ${DATAFOLD_RUN_TYPE} --commit-sha ${GIT_SHA}
        env:
          DATAFOLD_APIKEY: ${{ secrets.DATAFOLD_APIKEY }}
          DATAFOLD_RUN_TYPE: "${{ 'production' }}"
          GIT_SHA: "${{ github.ref == 'refs/heads/master' && github.sha }}"